# Generated by Django 4.2.7 on 2023-11-12 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glcm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrast_0', models.FloatField()),
                ('contrast_45', models.FloatField()),
                ('contrast_90', models.FloatField()),
                ('contrast_135', models.FloatField()),
                ('dissimilarity_0', models.FloatField()),
                ('dissimilarity_45', models.FloatField()),
                ('dissimilarity_90', models.FloatField()),
                ('dissimilarity_135', models.FloatField()),
                ('homogeneity_0', models.FloatField()),
                ('homogeneity_45', models.FloatField()),
                ('homogeneity_90', models.FloatField()),
                ('homogeneity_135', models.FloatField()),
                ('energy_0', models.FloatField()),
                ('energy_45', models.FloatField()),
                ('energy_90', models.FloatField()),
                ('energy_135', models.FloatField()),
                ('correlation_0', models.FloatField()),
                ('correlation_45', models.FloatField()),
                ('correlation_90', models.FloatField()),
                ('correlation_135', models.FloatField()),
                ('asm_0', models.FloatField()),
                ('asm_45', models.FloatField()),
                ('asm_90', models.FloatField()),
                ('asm_135', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Melon',
            fields=[
                ('kode_melon', models.TextField(max_length=10, primary_key=True, serialize=False, verbose_name='kode melon')),
                ('file_path', models.FileField(upload_to='storage/melon')),
                ('object_class', models.TextField(choices=[('MM', 'mature'), ('TM', 'raw'), ('BM', 'not melon')])),
                ('pub_date', models.DateField()),
                ('Glcm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ssm.glcm')),
            ],
        ),
    ]
