# Generated by Django 4.2.7 on 2023-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melon',
            name='file_path',
        ),
        migrations.AddField(
            model_name='melon',
            name='image',
            field=models.ImageField(default='no_im.jpeg', upload_to='melon/'),
        ),
    ]
