# Generated by Django 4.2.7 on 2023-11-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0002_remove_melon_file_path_melon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melon',
            name='image',
            field=models.ImageField(default='melon/no_im.jpeg', upload_to='melon/'),
        ),
    ]
