# Generated by Django 4.2.7 on 2023-11-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0003_alter_melon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melon',
            name='Glcm',
        ),
        migrations.AddField(
            model_name='melon',
            name='edge',
            field=models.ImageField(blank=True, null=True, upload_to='melon/edge'),
        ),
        migrations.AlterField(
            model_name='melon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='melon/raw/'),
        ),
        migrations.DeleteModel(
            name='Glcm',
        ),
    ]
