# Generated by Django 4.2.7 on 2023-11-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm', '0004_remove_melon_glcm_melon_edge_alter_melon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melon',
            name='crop',
            field=models.ImageField(blank=True, null=True, upload_to='melon/crop'),
        ),
        migrations.AddField(
            model_name='melon',
            name='edge_resize',
            field=models.ImageField(blank=True, null=True, upload_to='melon/resize'),
        ),
        migrations.AlterField(
            model_name='melon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='melon/raw'),
        ),
    ]
